- hosts: webservers
  user: webserver
  tasks:
    - name: 'Copy build to webserver'
      ansible.builtin.copy:
        src: target/spring-petclinic-2.7.0-SNAPSHOT.jar
        dest: /app/spring-petclinic-2.7.0-SNAPSHOT.jar
        owner: webserver
    - name: 'Run pet-clinic'
      shell: 'java -jar spring-petclinic-2.7.0-SNAPSHOT.jar'